### ISSUE TITLE
[Suggestion] Add Soul Fire'd compat

### ISSUE THREAD

**Issue by VoidLeech** [lilypuree/Decorative-Blocks#101]
Soul Fire'd adds an API for adding new Fire's and setting a mob on fire with such a Fire (which has both the visual difference and different damage properties (2x in the case of soul fire). I'd love to see it added as an optional dependency where the Soul Bonfire sets you alight with Soul Fire.

https://github.com/Nyphet/soul-fire-d/wiki/Using-the-API#set-on-fire

**Comment by lilypuree** [comment]
Implemented in version 4.1.1, thanks for the suggestion!
