### ISSUE TITLE
Rocky Dirt Recipe bug?

### ISSUE THREAD

**Issue by DesertNightFury** [lilypuree/Decorative-Blocks#104]
The latest version appears to have a potential bug, you cannot turn rocky dirt back into four normal dirt. I lost quite a bit of dirt this way. If it's not a bug but a change to the mod, perhaps a change back could be nice? It's convenient to store large quantities of the stuff. Thank you very much and I hope it isn't an inconvenience

**Comment by lilypuree** [comment]
Some recipes had been loast in the update, thanks for finding this out.
