### ISSUE TITLE
Palisades are a bit odd to break or mine

### ISSUE THREAD

**Issue by DesertNightFury** [lilypuree/Decorative-Blocks#105]
_(Very Sorry for submitting two bugs in a row, discovered this and the other one both very recently)_
Palisades seem to take the same very long time to mine no matter the tool being used on them, it's quality or enchantments? From what I can tell, mining them with an efficiency 5 diamond axe is no better than a stone axe, for example. It makes them a bit of a pain to clear out. Please fix if not intended behaviour? Would appreciate very much.

**Comment by lilypuree** [comment]
More issues for me to fix, the better! I'll look into what's causing this, too.

**Comment by DesertNightFury** [comment]
My thoughts are, based off of seeing Jade (what am I looking at sort of mod) not showing any specific tool to mine it with, there might be a missing tag there somewhere. Jade shows an axe for other wooden blocks. Hope this helps
(i do not know anything about mod coding)
