### ISSUE TITLE
Infinite thatch

### ISSUE THREAD

**Issue by MuteTiefling** [lilypuree/Decorative-Blocks#17]
Version: 6d

I know this is not exactly game breaking, but I thought you should know anyway.

While experimenting with thatch, I tried picking it up through various means. Buckets didn't work, but I soon found that the RFTools Builder with a pump card _can_. But when it is picked up out of the world, it doesn't actually remove the source block. So if set to run on repeat, the pump will pick up an unlimited amount of thatch.

It can then be placed down in a similar way, using mods that can place fluids. So I guess it would be good for a nasty prank of filling in someone's base with thatch >.>

**Comment by SelkeGore** [comment]
abusing this to grief multiple friends bases before its patched, ty
