### ISSUE TITLE
Unable to make Acacia Beam in Valhelsia 2.

### ISSUE THREAD

**Issue by universe74** [lilypuree/Decorative-Blocks#18]
Acacia beam recipe only makes acacia wood.  Unable to make acacia beams in valhelsia 2.

**Comment by lilypuree** [comment]
The recipes are changeable with datapacks. Contact the Valhelsia 2 team to add non-conflicting recipes, or use a mod called [polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph).
