### ISSUE TITLE
[1.16] Conflict with Biomes O' Plenty

### ISSUE THREAD

**Issue by Khytwel** [lilypuree/Decorative-Blocks#21]
Hi,

There's a conflict with Decorative Blocks and Biomes O' Plenty. Here is the error when I want to create a new world:
![image](https://user-images.githubusercontent.com/54046029/87350791-a688d280-c558-11ea-9389-2cccb11279ac.png)

Here are the latest logs:
https://pastebin.com/fMvhuGg7

Version Decorative Blocks: 1.16-0.2
Version Biomes O' Plenty: 1.16.1-11.0.0.376

**Comment by lilypuree** [comment]
probably fixed by now

**Comment by Khytwel** [comment]
Yep, fixed, thanks you!
