### ISSUE TITLE
Extinguished braziers still act as a light source

### ISSUE THREAD

**Issue by Extegral** [lilypuree/Decorative-Blocks#29]
I am currently using 1.16.1-1.4 version of Decorative Blocks. Braziers appear to still give off their full light whenever put out:

![image](https://user-images.githubusercontent.com/47505981/92180721-09effc00-ee48-11ea-97a5-2b255f6e24ef.png)

Presumably this is an oversight. If it was intended, however, doesn't make much logical sense.

**Comment by lilypuree** [comment]
Thanks for reporting, it should be fixed now.
