### ISSUE TITLE
[Bug] Missing license Decorative-Blocks and Decorative-Blocks-Compat

### ISSUE THREAD

**Issue by DerHofnarr** [lilypuree/Decorative-Blocks#32]
Installed the mod today and got the massage "Missing license information in file Mod file: (Link to decorative-blocks and decorative-blocks-compat)". 

Crashlog: https://paste.gg/p/anonymous/97d883f4af4c47a5aaf9b80d7ae7d6f9
Screenshot: https://pasteboard.co/JtU7Y38.png

EDIT
My OS: Ubuntu 20.04.1 LTS
Gnome: 3.36.3
Core: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8
GPU 1: VGA compatible controller: Intel Corporation HD Graphics 630
GPU 2: 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (< My main GPU i just use this one for MC)
in case you need it :-)

Any ideas how to fix this? i really want to check out your mod.

Have a nice day. Cheers :-)

**Comment by lilypuree** [comment]
the compat mod isn't updated yet, will take some time to do so. Meanwhile the 1.16.2 version of Decorative Blocks might work for 1.16.3 as well, though I have to check.

**Comment by DerHofnarr** [comment]
ok thanks for the reply. i will test it out soon.

Cheers :-)

**Comment by DerHofnarr** [comment]
Yep the 1.16.2 version works perfectly fine. thanks so far for that.

Cheers :-)
