### ISSUE TITLE
Enemy mobs able to stand inside and move through wooden beams

### ISSUE THREAD

**Issue by Heideho** [lilypuree/Decorative-Blocks#37]
As the title says, the recent fix stopped the player being able to walk through wooden beams but enemies such as skeletons, zombies, creepers etc can still stand inside and even pass through the wooden beams.

**Comment by lilypuree** [comment]
What mods are you using with Decorative Blocks?

**Comment by Heideho** [comment]
Well this is an awkward mistake but when updating my mod list i thought i had downloaded the version with the fix but had accidentally copied the old one across, my bad "/
