### ISSUE TITLE
Suggestion: Add config option for fire damage

### ISSUE THREAD

**Issue by Sandriell** [lilypuree/Decorative-Blocks#39]
It would be nice if fire damage could be disabled on the braziers. Right now I have be extremely careful with how and where I use the braziers to prevent mobs from other mods getting killed on them, like Minecolonies NPCs.

**Comment by lilypuree** [comment]
1.7.1 update will make mobs no longer pathfind over braziers, and made them not damage mobs when they aren't directly above it
