### ISSUE TITLE
Server crash on item drop 1.15.2

### ISSUE THREAD

**Issue by JMZED** [lilypuree/Decorative-Blocks#4]
Server crashes when you drop an item on 1.15.2 mod version 6.
Crash report seems to be related to the creation of bonfires. See image https://i.imgur.com/sVndCjn.png

**Comment by lilypuree** [comment]
Oops, seems like I was using a clientside only method. Thanks for reporting, the fixed version will be uploaded soon!

**Comment by lilypuree** [comment]
The bug fix is uploaded, it should hopefully fix it. I will keep this open until you can confirm.

**Comment by JMZED** [comment]
Seems to be working fine. I will let you know if the issue happens again.
