### ISSUE TITLE
server and client crashes when entities collide with Brazier block

### ISSUE THREAD

**Issue by Rutes** [lilypuree/Decorative-Blocks#41]
Getting crashes whenever an entity collides with a Brazier.
It happens on client-side consistently when a player tries to walk on a Brazier.

On server-side, we've seen it when a mob randomly walks into a Brazier.

https://gist.github.com/Rutes/b04ca7762945db240180c10d0e8de458

**Comment by lilypuree** [comment]
fixed by https://github.com/lilypuree/Decorative-Blocks/commit/10f2de7ba473e73b230314f7676b76d7ba2cf652
