### ISSUE TITLE
[Bug] Variant Recipe Issue

### ISSUE THREAD

**Issue by RotokEralil** [lilypuree/Decorative-Blocks#62]
When crafting, if the same object can be crafting with different materials for a variant type (such as doors, stairs, etc), but the following items cycle through in the same slot
even though they are not variant recipes of the same item: Bar Panel, Soul Brazier, Brazier, Big Chain, Lattice, Soul Chandelier, Chandelier, Rocky Dirt.

Edit: Additional crafting recipe issue; all items from this and decorative winter show up in the recipe book right away, without having to discover them.

**Comment by lilypuree** [comment]
Fixed by commit 42eb9d18434139e127c0233064fc04c850655d24
