### ISSUE TITLE
ClassNotfoundExeption

### ISSUE THREAD

**Issue by JammingEnd** [lilypuree/Decorative-Blocks#64]
[latest.log](https://github.com/lilypuree/Decorative-Blocks/files/7913951/latest.log)

this happened recently. it even happens after i uninstalled the mod.

**Comment by lilypuree** [comment]
The log shows you have several versions of mods installed at once... you should be using only one jar at a time...

**Comment by JammingEnd** [comment]
hm curseforge isnt deleting pre-update files it seems. so its not a mod problem :)
