### ISSUE TITLE
`ArrayIndexOutOfBoundsException` potentially due to non-thread-safe code.

### ISSUE THREAD

**Issue by falxie** [lilypuree/Decorative-Blocks#77]
Running version 2.1.1 and Forge 40.1.74 can sometimes result in errors during mod setup. The errors have a striking resemblance to the incompatibilities reported between https://github.com/moddingplayground/twigs-forge/issues/5 and https://github.com/1mphuls3/CreateCafe-1.18/issues/38.

I think in this case it's possible that the incompatibility is between The Wild Backport and this mod both trying to register flammable blocks in an asynchronous event.

See https://github.com/ItsBlackGear/TheWildBackport-Master/issues/2

[logs.zip](https://github.com/lilypuree/Decorative-Blocks/files/9463349/logs.zip)

**Comment by lilypuree** [comment]
Closed by [158d2f4](https://github.com/lilypuree/Decorative-Blocks/commit/158d2f4dbdc188929a1610a354237efc7dd6dc40)
