### ISSUE TITLE
Unable to destroy thatch source blocks with hoe

### ISSUE THREAD

**Issue by Tarliman** [lilypuree/Decorative-Blocks#79]
Running MC 1.18.2 under PrismLauncher 5.0

Log at https://mclo.gs/Fgq0I3I

In both Creative and Survival mode, thatch source blocks do not break when hit with a hoe, iron or diamond, enchanted or not, or any other tool. Thatch source blocks can be replaced with andesite (used for test) with no issues, destroying the source and removing the thatch flow. Thatch source blocks will burn, if fire is set below or beside them where it can spread to the source block. 

PrismLauncher export, with game save, available upon request.

Mods:
-rwx------  1 xxxxxxxx xxxxxxxx    42265 Oct 19 16:32 AkashicTome-1.5-20.jar
-rwx------  1 xxxxxxxx xxxxxxxx    46304 Oct 19 16:32 appleskin-forge-mc1.18.2-2.4.1.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx  6828185 Nov  2 17:34 ars_nouveau-1.18.2-2.8.0.jar
-rwx------  1 xxxxxxxx xxxxxxxx    42733 Oct 19 16:32 AutoRegLib-1.7-53.jar
-rwx------  1 xxxxxxxx xxxxxxxx   621815 Oct 19 16:32 balm-3.2.0+0.jar
-rwx------  1 xxxxxxxx xxxxxxxx   312212 Oct 19 16:32 Bookshelf-Forge-1.18.2-13.2.50.jar
-rwx------  1 xxxxxxxx xxxxxxxx 11422451 Oct 19 16:32 Botania-1.18.2-435.jar
-rwx------  1 xxxxxxxx xxxxxxxx 14058764 Oct 19 16:32 ChinjufuMod[1.18.2]6.2.4.jar
-rwx------  1 xxxxxxxx xxxxxxxx    16764 Oct 19 16:32 Clumps-forge-1.18.2-8.0.0+15.jar
-rwx------  1 xxxxxxxx xxxxxxxx   207117 Oct 19 16:32 Connectible Chains-forge-1.18.2-2.1.1.jar
-rwx------  1 xxxxxxxx xxxxxxxx 13942567 Oct 19 16:32 create-1.18.2-0.5.0.e.jar
-rwx------  1 xxxxxxxx xxxxxxxx  2721352 Oct 19 16:32 createdeco-1.2.11-1.18.2.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx   267100 Oct 24 22:33 creeperconfetti-3.11.jar
-rwx------  1 xxxxxxxx xxxxxxxx   167776 Oct 19 16:32 Cucumber-1.18.2-5.1.3.jar
-rwx------  1 xxxxxxxx xxxxxxxx   270867 Oct 19 16:32 curios-forge-1.18.2-5.0.7.1.jar
-rwx------  1 xxxxxxxx xxxxxxxx    32640 Oct 19 16:32 CuriosQuarkOBP-1.18.2-1.1.4.jar
-rwx------  1 xxxxxxxx xxxxxxxx   274348 Oct 19 16:32 Decorative Blocks Compat-forge-1.18.2-2.1.0.jar
-rwx------  1 xxxxxxxx xxxxxxxx   468604 Oct 19 16:32 Decorative Blocks-forge-1.18.2-2.1.2.jar
-rwx------  1 xxxxxxxx xxxxxxxx    60879 Oct 19 16:32 EnchantmentDescriptions-Forge-1.18.2-10.0.9.jar
-rwx------  1 xxxxxxxx xxxxxxxx     8873 Oct 19 16:32 FastLeafDecay-28.jar
-rwx------  1 xxxxxxxx xxxxxxxx    14792 Oct 19 16:32 feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
-rwx------  1 xxxxxxxx xxxxxxxx   544022 Oct 19 16:32 flywheel-forge-1.18.2-0.6.5.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx  2982856 Nov  2 17:34 geckolib-forge-1.18-3.0.54.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx  1081495 Nov  2 17:34 jei-1.18.2-forge-10.2.1.283.jar
-rwx------  1 xxxxxxxx xxxxxxxx    26938 Oct 19 16:32 jeiintegration_1.18.2-9.0.0.37.jar
-rwx------  1 xxxxxxxx xxxxxxxx   878620 Oct 19 16:32 LibX-1.18.2-3.2.19.jar
-rwx------  1 xxxxxxxx xxxxxxxx  1449569 Oct 19 16:32 mcw-furniture-3.0.2-mc1.18.2.jar
-rwx------  1 xxxxxxxx xxxxxxxx   242271 Oct 19 16:32 mcw-lights-1.0.4-mc1.18.2.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx  1214288 Nov  2 17:34 modonomicon-1.18.2-1.6.1.jar
-rwx------  1 xxxxxxxx xxxxxxxx    76344 Oct 19 16:32 MouseTweaks-forge-mc1.18-2.21.jar
-rwx------  1 xxxxxxxx xxxxxxxx   272819 Oct 19 16:32 MysticalAgradditions-1.18.2-5.1.2.jar
-rwx------  1 xxxxxxxx xxxxxxxx  1749522 Oct 19 16:32 MysticalAgriculture-1.18.2-5.1.2.jar
-rwx------  1 xxxxxxxx xxxxxxxx  4598928 Oct 19 16:32 mysticalworld-1.18.2-0.4.7.28.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx  2173724 Nov  2 17:34 MythicBotany-1.18.2-2.1.14.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx  5055681 Nov  2 17:34 occultism-1.18.2-1.48.0.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx 36569914 Nov  2 17:34 Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx  1013595 Nov  2 17:34 pamhc2crops-1.18.2-1.0.5.jar
-rwx------  1 xxxxxxxx xxxxxxxx   437561 Oct 19 16:32 pamhc2foodcore-1.18.2-1.0.3.jar
-rwx------  1 xxxxxxxx xxxxxxxx  2098352 Oct 19 16:32 pamhc2foodextended-1.18.2-1.0.5.jar
-rwx------  1 xxxxxxxx xxxxxxxx   553180 Oct 19 16:32 pamhc2trees-1.18.2-1.0.3.jar
-rwx------  1 xxxxxxxx xxxxxxxx   631415 Oct 19 16:32 Patchouli-1.18.2-71.1.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx   255211 Oct 30 08:02 polymorph-forge-1.18.2-0.45.jar
-rwx------  1 xxxxxxxx xxxxxxxx 13743162 Oct 19 16:32 Quark-3.2-358.jar
-rwx------  1 xxxxxxxx xxxxxxxx     1892 Oct 19 16:32 QuarkOddities-1.18.jar
-rwx------  1 xxxxxxxx xxxxxxxx  6217276 Oct 19 16:32 repurposed_structures_forge-5.1.14+1.18.2.jar
-rwx------  1 xxxxxxxx xxxxxxxx    14146 Oct 19 16:32 Runelic-Forge-1.18.2-11.0.1.jar
-rwx------  1 xxxxxxxx xxxxxxxx   734191 Oct 19 16:32 sophisticatedbackpacks-1.18.2-3.18.29.718.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx   924108 Nov  2 17:34 sophisticatedcore-1.18.2-0.5.15.141.jar
-rwx------  1 xxxxxxxx xxxxxxxx    96811 Oct 19 16:32 TerraBlender-forge-1.18.2-1.2.0.126.jar
-rwx------  1 xxxxxxxx xxxxxxxx   124371 Oct 19 16:32 Thatched-forge-1.18.2-1.1.0.jar
-rwx------  1 xxxxxxxx xxxxxxxx   330953 Oct 19 16:32 theoneprobe-1.18-5.1.2.jar
-rwx------  1 xxxxxxxx xxxxxxxx   357620 Oct 19 16:32 waystones-forge-1.18.2-10.1.0.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx  1238690 Nov  2 17:34 Xaeros_Minimap_22.16.0_Forge_1.18.2.jar
-rw-r--r--  1 xxxxxxxx xxxxxxxx   701302 Nov  2 17:34 XaerosWorldMap_1.28.1_Forge_1.18.2.jar

**Comment by syntheer** [comment]
You can remove it with a Bucket

**Comment by lilypuree** [comment]
You can remove it by using the hoe. They do not break because it is not a block.
