### ISSUE TITLE
[Suggestion]  little fix in Korean language

### ISSUE THREAD

**Issue by MilkissWhite** [lilypuree/Decorative-Blocks#8]
First, this mod have very nice korean translation. I must say. this is just a little issue.
 I think name of items with Jungle wooden and Acacia wooden are little different from vanilla taste.

 in vanilla minecraft, items from jungle wood/acacia wood have names like "정글 나무 ~~~"/"아카시아나무 ~~~". this mod have only "정글 ~~~"/"아카시아 ~~~".

 for example, jungle wood related items in vanilla :
 정글 나무 판자, 정글나무 원목(this is only item have "정글+나무" without space bar), 정글 나무 계단, 정글 나무 묘목, 정글 나무 울타리, 정글 나무 문, 정글 나무 보트, etc...
 in this mod : 
 정글 들보, 정글 말뚝, 정글 의자, 정글 지지대

 you can see what is different from vanilla.

 if fix this names, I think it looks more close to vanilla taste.
 
[ko_kr.zip](https://github.com/lilypuree/Decorative-Blocks/files/4340648/ko_kr.zip)

 this file already fixed that lines. please use this if you think same as me.

thx for reading and nice mod.

**Comment by lilypuree** [comment]
사실 한국인이에요ㅎㅎ 바닐라 마크를 한글로 안해봐서 그건 몰랐군요. 감사합니다!

**Comment by MilkissWhite** [comment]
앗 한국인이셨다니... 영어 실력도 안되는데 고생고생해서 적었건만 ㅠㅠ
