### ISSUE TITLE
Missing datapack

### ISSUE THREAD

**Issue by innerdev** [lilypuree/Decorative-Blocks#85]
Hello!
 
Dear sir, can you help me, please?

I’m trying to install your mod Decorative Blocks. But when in put the jar file into mods directory on my dedicated minecraft (v1.9.2 with forge 43.2.3) server I’m getting this error: missing data pack mod:decoration_mod.
 
Where can I download the datapack? Have no idea what is it, haha, but I’m sure I need it.

**Comment by TheManFran** [comment]
I have the same problem. Have you found a solution for this?

**Comment by lilypuree** [comment]
This does not seem to be the problem of Decorative Blocks. Please check if it happens in an isolated instance.
