### ISSUE TITLE
Release on Modrinth.com

### ISSUE THREAD

**Issue by CodeF53** [lilypuree/Decorative-Blocks#92]
Modrinth is an alternative to Curseforge which is way better in a few key aspects:
  -  Proper filtering
     - on Curseforge you can search for 1.17 mods, or fabric mods, not 1.17 fabric mods
     - client/server mod filters
  -  Fast searches
     -  It takes nanoseconds for the search results to update to what you have typed, as opposed to the 3-5 seconds Curseforge does
  - Easier API integration
     - Well documented, easy to use api
     - You can ask for support from actual humans

**Comment by Zorklis** [comment]
Fabric community on Modrinth would welcome this mod and I just found out about it.

**Comment by lilypuree** [comment]
The mod is under review on modrinth
