### ISSUE TITLE
V4.0.0 crashes on 1.20.1

### ISSUE THREAD

**Issue by adozenlionsroaring** [lilypuree/Decorative-Blocks#96]
Forge version: 47.2.0
Minecraft version: 1.20.1
Mod version: 4.0.0

For me, the game gives an Error 1 and crashes before it even generates a log. However, two people have been able to provide these logs on Curseforge:

---

Mixin apply failed decorative_blocks.mixins.json:ItemEntityMixin -> net.minecraft.world.entity.item.ItemEntity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method getItem in decorative_blocks.mixins.json:ItemEntityMixin was not located in the target class net.minecraft.world.entity.item.ItemEntity. Using refmap decorative_blocks.refmap.json

org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getItem in decorative_blocks.mixins.json:ItemEntityMixin was not located in the target class net.minecraft.world.entity.item.ItemEntity. Using refmap decorative_blocks.refmap.json

---

[pool-4-thread-1/FATAL]: Mixin apply failed decorative_blocks.mixins.json:ItemEntityMixin -> net.minecraft.world.entity.item.ItemEntity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method getItem in decorative_blocks.mixins.json:ItemEntityMixin was not located in the target class net.minecraft.world.entity.item.ItemEntity. Using refmap decorative_blocks.refmap.json

org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getItem in decorative_blocks.mixins.json:ItemEntityMixin was not located in the target class net.minecraft.world.entity.item.ItemEntity. Using refmap decorative_blocks.refmap.json

**Comment by Cikodel** [comment]
Same problem here

**Comment by ModernGamingWorld** [comment]
Same Problem here, just use one version before the new one and you wont crash for now

**Comment by lilypuree** [comment]
Fixed
