### ISSUE TITLE
Just started crashing after update 1.20.1-4.0.0

### ISSUE THREAD

**Issue by Zexiona** [lilypuree/Decorative-Blocks#99]
Causes error code one within personal modpack when updated to the current version (4.0.0) on 1.20.1. Can provide anything needed.

**Comment by lilypuree** [comment]
Please provide the crash & debug log

**Comment by Zexiona** [comment]
Making it reoccur to provide those. For some reason it didn't provide a crash log the first time.

**Comment by Zexiona** [comment]
This is unfortunately all i can provide. it won't provide a crash log.
[latest.log](https://github.com/lilypuree/Decorative-Blocks/files/13851954/latest.log)

[debug.log](https://github.com/lilypuree/Decorative-Blocks/files/13851955/debug.log)

**Comment by lilypuree** [comment]
I have reuploaded the 4.0.0 file immediately after deleting it because I have made a mistake the first time of not including the refmaps. It seems like you have unfortunately downloaded the deleted version. This will not happen in the current 4.0.0 version.

**Comment by mkern1200** [comment]
This error is still occurring when using the Fabric version uploaded to Modrinth for v4.0.0, which looks like it was uploaded the day before this issue was reported.  Would it be possible to update the download on Modrinth to the fixed version?

**Comment by lilypuree** [comment]
@mkern1200 If the issue is happening on fabric, please create a new issue with the crash/debug logs.
